/** Irregular verb groups: base form first, then every other form. */
export const IRREGULAR_GROUPS: readonly string[] = [
  'be am is are was were been being',
  'have has having had',
  'do does doing did done',
  'go goes going went gone',
  'arise arose arisen',
  'awake awoke awoken',
  'bear bore born borne',
  'beat beaten',
  'become became',
  'begin began begun',
  'bend bent',
  'bind bound',
  'bite bit bitten',
  'bleed bled',
  'blow blew blown',
  'break broke broken',
  'breed bred',
  'bring brought',
  'build built',
  'burn burnt burned',
  'buy bought',
  'catch caught',
  'choose chose chosen',
  'cling clung',
  'come came',
  'creep crept',
  'deal dealt',
  'dig dug',
  'dive dove dived',
  'draw drew drawn',
  'dream dreamt dreamed',
  'drink drank drunk',
  'drive drove driven',
  'dwell dwelt',
  'eat ate eaten',
  'fall fell fallen',
  'feed fed',
  'feel felt',
  'fight fought',
  'find found',
  'flee fled',
  'fling flung',
  'fly flew flown',
  'forbid forbade forbidden',
  'foresee foresaw foreseen',
  'foretell foretold',
  'forget forgot forgotten',
  'forgive forgave forgiven',
  'forsake forsook forsaken',
  'freeze froze frozen',
  'get got gotten',
  'give gave given',
  'grind ground',
  'grow grew grown',
  'hang hung hanged',
  'hear heard',
  'hide hid hidden',
  'hold held',
  'keep kept',
  'kneel knelt',
  'know knew known',
  'lay laid',
  'lead led',
  'lean leant leaned',
  'leap leapt leaped',
  'learn learnt learned',
  'leave left',
  'lend lent',
  'lie lay lain lying',
  'light lit lighted',
  'lose lost',
  'make made',
  'mean meant',
  'meet met',
  'mislead misled',
  'mistake mistook mistaken',
  'misunderstand misunderstood',
  'mow mowed mown',
  'outdo outdid outdone',
  'overcome overcame',
  'overdo overdid overdone',
  'overhear overheard',
  'override overrode overridden',
  'oversee oversaw overseen',
  'overtake overtook overtaken',
  'overthrow overthrew overthrown',
  'pay paid',
  'plead pled pleaded',
  'prove proved proven',
  'rebuild rebuilt',
  'redo redid redone',
  'rewrite rewrote rewritten',
  'ride rode ridden',
  'ring rang rung',
  'rise rose risen',
  'run ran',
  'say said',
  'see saw seen',
  'seek sought',
  'sell sold',
  'send sent',
  'sew sewed sewn',
  'shake shook shaken',
  'shine shone',
  'shoot shot',
  'show showed shown',
  'shrink shrank shrunk',
  'sing sang sung',
  'sink sank sunk',
  'sit sat',
  'slay slew slain',
  'sleep slept',
  'slide slid',
  'sling slung',
  'smell smelt smelled',
  'sow sowed sown',
  'speak spoke spoken',
  'speed sped',
  'spell spelt spelled',
  'spend spent',
  'spill spilt spilled',
  'spin spun',
  'spit spat',
  'spoil spoilt spoiled',
  'spring sprang sprung',
  'stand stood',
  'steal stole stolen',
  'stick stuck',
  'sting stung',
  'stink stank stunk',
  'stride strode stridden',
  'strike struck stricken',
  'string strung',
  'strive strove striven',
  'swear swore sworn',
  'sweep swept',
  'swell swelled swollen',
  'swim swam swum',
  'swing swung',
  'take took taken',
  'teach taught',
  'tear tore torn',
  'tell told',
  'think thought',
  'throw threw thrown',
  'tread trod trodden',
  'undergo underwent undergone undergoes',
  'understand understood',
  'undertake undertook undertaken',
  'undo undid undone undoes',
  'uphold upheld',
  'wake woke woken',
  'wear wore worn',
  'weave wove woven',
  'weep wept',
  'win won',
  'wind wound',
  'withdraw withdrew withdrawn',
  'withhold withheld',
  'withstand withstood',
  'wring wrung',
  'write wrote written',
];
